# Generated by Django 4.1.6 on 2023-02-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_categories_alter_room_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(max_length=160, null=True, unique=True),
        ),
    ]
