# Generated by Django 4.1.6 on 2023-02-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_categories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(max_length=160, null=True, unique=True, verbose_name='SLUG'),
        ),
    ]
