# Generated by Django 4.1.6 on 2023-02-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
