# Generated by Django 4.1.6 on 2023-02-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_room_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
