# Generated by Django 4.1.6 on 2023-03-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
